import os


OLLAMA_URL = os.getenv("LINUX_ASSISTANT_OLLAMA_URL", "http://127.0.0.1:11434/api/chat")
MODEL = os.getenv("LINUX_ASSISTANT_MODEL", "gpt-oss:20b")
MAX_TOOL_ROUNDS = int(os.getenv("LINUX_ASSISTANT_MAX_TOOL_ROUNDS", "8"))
MAX_DUPLICATE_TOOL_CALLS = int(
    os.getenv("LINUX_ASSISTANT_MAX_DUPLICATE_TOOL_CALLS", "1")
)
MAX_HISTORY_MESSAGES = int(os.getenv("LINUX_ASSISTANT_MAX_HISTORY_MESSAGES", "80"))
MAX_HISTORY_TOKENS = int(os.getenv("LINUX_ASSISTANT_MAX_HISTORY_TOKENS", "12000"))
COMMAND_TIMEOUT = int(os.getenv("LINUX_ASSISTANT_COMMAND_TIMEOUT", "30"))
OLLAMA_TIMEOUT = int(os.getenv("LINUX_ASSISTANT_OLLAMA_TIMEOUT", "90"))
OLLAMA_RETRIES = int(os.getenv("LINUX_ASSISTANT_OLLAMA_RETRIES", "2"))
OLLAMA_RETRY_BACKOFF = float(os.getenv("LINUX_ASSISTANT_OLLAMA_RETRY_BACKOFF", "0.25"))
MAX_OUTPUT = int(os.getenv("LINUX_ASSISTANT_MAX_OUTPUT", "12000"))
MAX_FILE_SIZE = int(os.getenv("LINUX_ASSISTANT_MAX_FILE_SIZE", str(256 * 1024)))
